### ISSUE TITLE
Need installer binary

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs-shipyard/station#16]
not high priority, but we eventually need a single binary that will install ipfs and the electron shell app.

**Comment by diasdavid** [comment]
you mean like a .pkg that does both?

Currently electron does the IPFS install through ipfsd if IPFS is not installed yet, is that good enough?

**Comment by jbenet** [comment]
i think the github.com/ipfs/distribution pages we discussed will be good enough

**Comment by jbenet** [comment]
and yeah, we'll have an OSX .pkg installer there for the ipfs toolchain.

we need to figure out the semantics of having `ipfs` available locally and from the installed node_modules... it could get confusing
