### ISSUE TITLE
Better handling of already running ipfs daemon

### ISSUE THREAD

**Issue by jbenet** [ipfs-shipyard/station#19]
![](http://gateway.ipfs.io/ipfs/Qmf1yUmCUH9uAdrmU21nCxUZihHV8YbH1v5G1JAmhyHs6Z/cap.png)

**Comment by jbenet** [comment]
i think it was when i started this node while a background daemon was running?

**Comment by CaioAlonso** [comment]
+1
![Screenshot](http://i.imgur.com/MTjySiL.png)
These are the steps that I did:
1. ```$ ipfs daemon```
2. ```$ npm start```
3. Turn IPFS Node on
4. Ctrl-C the daemon

**Comment by jbenet** [comment]
this thing runs its own daemon. you dont need to run it yourself. it's port clashing

also, we need a waaaay better error for that. ugh

**Comment by CaioAlonso** [comment]
@jbenet yes, a simple port conflict shouldn't crash it.

**Comment by hacdias** [comment]
Already a bit better than what it was in 2015. Although, there is still a lot of room to improvement. Will continue this on #527.
