### ISSUE TITLE
windows installer

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs-shipyard/station#20]
as a followup to #16, we can use https://github.com/atom/grunt-electron-installer to build a windows installer for us, it looks pretty nice and should help a lot with getting people to have ipfs installed.

**Comment by whyrusleeping** [comment]
This one looks better: https://github.com/maxogden/electron-packager

**Comment by diasdavid** [comment]
We currently ship .exe for Windows (`npm run dist-all`) but it would be nice if we would have a 'installer dialog' like Windows users are used to.

![image](https://cloud.githubusercontent.com/assets/1211152/9149962/46f99858-3dc3-11e5-9ccb-9d6521f0cbc6.png)

Or maybe nowadays with Win 8.1, Win 10 and their app store the convention is different. Is there some Windows users that can advise?

**Comment by jbenet** [comment]
cc @gatesvp

**Comment by whyrusleeping** [comment]
the electron package will build that installer dialog

**Comment by gatesvp** [comment]
While I won't argue with a Windows Installer, it's kind of a weird set up
in the Windows world.

IPFS on Windows should run as a service, kind of like BitTorrent. However
right now, it is only available as a command line app. So what do we
bundle? If the installer runs IPFS as a service, then maybe we can set up a
shortcut to the "localhost" in a browser.

If we want IPFS as just a CLI tool, then we can use chocolatey.org and
build something that targets CLI users. Of course if we have the above
service installer, Chocolatey can run that installer as well.

I seem to recall that we had investigated a Windows service wrapper a few
months back. Did they ever get installed for setup?

**Comment by jbenet** [comment]
some quick thoughts: 

---

@whyrusleeping 
> the electron package will build that installer dialog

oh yeah? nice

---

@gatesvp 

> IPFS on Windows should run as a service, kind of like BitTorrent. However right now, it is only available as a command line app. So what do we bundle? If the installer runs IPFS as a service, then maybe we can set up a shortcut to the "localhost" in a browser.

Yeah, this repo (electron-app) makes a tray-hosted service. try it out!

**Comment by gatesvp** [comment]
Looked at the screenshots for all these and this process makes sense. Do we have these binaries built anywhere so that I can test them out? Or are we waiting for them to get built?

**Comment by whyrusleeping** [comment]
@gatesvp we need windows help! (could you stop by irc for a chat?)

**Comment by whyrusleeping** [comment]
(although, not entirely related to this repo)

**Comment by bogdoslav** [comment]
Hello! I have created insttaller for windows: https://github.com/bogdoslav/ipfs-windows-installer
Firewall rules and windows start-up task created during install.
Please test and give a feedback.

**Comment by lidel** [comment]
Another piece of the puzzle: https://github.com/marcin212/ipfs-gui 
It does not touch firewall, but provides basic GUI via tray icon: 

> ![2017-11-22 10_30_18-](https://user-images.githubusercontent.com/157609/33119727-29d3a124-cf70-11e7-8dab-9b6b071dcd18.png)
