### ISSUE TITLE
Add ~~`right click`~~ `alt click` for settings and quit

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/station#28]
with -> https://github.com/atom/electron/blob/master/docs/api/tray.md#event-right-clicked

**Comment by diasdavid** [comment]
Actually, following the pattern found in other apps. It should be `alt+click` and not `right click`

**Comment by diasdavid** [comment]
PR to free key+click events https://github.com/maxogden/menubar/pull/50

**Comment by jbenet** [comment]
:+1:

**Comment by hacdias** [comment]
Settings and Exit will be available as a context menu once #516 is merged. I'm closing this. 😄
