### ISSUE TITLE
menu bar improvements

### ISSUE THREAD

**Issue by jbenet** [ipfs-shipyard/station#3]
the menu bar should give some info on the node, like:
- say what ports it's on (swarm, gateway, api)
- stats (maybe under a sub-menu):
  - uptime
  - # of peers connected
  - bandwidth numbers

and maybe it should have some more options:
- "Open" should be "Open Web Console" or "Open Web UI" or "Open Admin Console" or something...
- "Open Web Console in Browser" (opens in a normal browser, just in case)
- "Configuration" (opens config in an editor)
- "Restart" (kills the node and reboots it)
- "Check for Update" (checks for update-- we need to figure this out)

**Comment by bcomnes** [comment]
I couldn't find a way to dynamically update the tray menu contents last I checked but I'm totally :+1: on these stats.  https://github.com/maxogden/menubar Fakes a menu using html/css and is dynamically updatable if we can't dynamically update the native menu system.

**Comment by jbenet** [comment]
html menu means we can draw whatever we want, [which is nice](https://www.youtube.com/watch?v=pBWcRqPesws)

otoh, native menus are more ok with people. im down for whatever, if we do html, we should use it creatively.

**Comment by krl** [comment]
You can update the context menu, but that also closes the menu for the user, for now i'm doing something like this:
 
![menu](https://cloud.githubusercontent.com/assets/59379/8146104/ee13c03c-1226-11e5-96bc-b9758b390b32.png)

@jbenet

**Comment by jbenet** [comment]
@krl good stuff! 

- "run daemon" is not very intuitive for end users. This is a tricky UI, because we want to give people the idea of "turning something On and Off". maybe "connect to swarm" could be grayed out when daemon is offline.

Maybe something like:

```
IPFS local node running ...
Stop IPFS node
[ ] Online (connected to swarm)
---
Open Console Window
Open Console in Browser
---
Exit
```
Hmm not sure.  Maybe:

![](https://www.evernote.com/l/AMbjAGTTLV5Cua9dCEuOur_f0zGRqKpqoKAB/image.png)

(Experimenting. probably want a real designer to figure this out, not me)

**Comment by jbenet** [comment]
btw, we can use arbitrary web page as a menu. see https://github.com/maxogden/ScreenCat

**Comment by krl** [comment]
jbenet: in osx that is, it seems like linux/windows support for this is not in. i could look at enabling that, but do we want to go that path?

**Comment by krl** [comment]
i'm really into your designs though.

**Comment by krl** [comment]
An alternative in the meantime i just thought of colud be using radio buttons.
 
( ) offline
( ) run local node
( ) run connected node
----
[ ] check for updates

**Comment by jbenet** [comment]
@krl i think we'll get a lot more mileage out of an HTML window.

**Comment by krl** [comment]
from: https://github.com/atom/electron/blob/master/docs/api/tray.md

Platform limitations:

    On OS X clicked event will be ignored if the tray icon has context menu.
    On Linux app indicator will be used if it is supported, otherwise GtkStatusIcon will be used instead.
    App indicator will only be showed when it has context menu.
    When app indicator is used on Linux, clicked event is ignored.

So if you want to keep exact same behaviors on all platforms, you should not rely on clicked event and always attach a context menu to the tray icon.


It seems to be the case that you cannot even get the 'clicked' event in gnome for example.

**Comment by krl** [comment]
hmm actually: https://github.com/atom/electron/pull/1741

I'll investigate this.

**Comment by bcomnes** [comment]
Those mockups look amazing!  I don't know how to do the cool dropbox style window arrow, but everything else looks totally doable and nice.

**Comment by jbenet** [comment]
@bcomnes on the transparency, we could actually have a nice space background instead of making it transparent, which gets us 50% of the way there.

@krl do you need frontend help to make all this look super nice? If it's not your thing we can find someone who is good at it. (we should allocate resources optimally)

**Comment by krl** [comment]
Yeah, i'm not spending a lot of time on the design now, just getting something that looks decent and that works. I think having a designer go over it would be ideal.

**Comment by whyrusleeping** [comment]
how would the drop 'down' thing work for people (like me) who have their tray at the bottom of the screen?

**Comment by jbenet** [comment]
drop up! /o\

**Comment by krl** [comment]
Ok, the stats shown in your example, is there a way to actually get them from the api, or from the client without daemon running?

**Comment by jbenet** [comment]
@krl maybe we should add an `ipfs repo stat` command

**Comment by krl** [comment]
+1 repo stat command

**Comment by jbenet** [comment]
@krl let's try getting it in this next sprint for you.

**Comment by diasdavid** [comment]
@jbenet what are your thoughts on a `settings`/`preferences` page, UI'wise?

**Comment by jbenet** [comment]
@diasdavid yeah we can do settings. what are the things we would have there?

**Comment by diasdavid** [comment]
Some that I have in my mind
- repo/folder
- ports
- reset Node (updating key pair)
- start on boot
- bandwith used
- language
- link to help
- user

**Comment by Dignifiedquire** [comment]
@diasdavid @jbenet let's extract individual items from here into separate issues.

**Comment by diasdavid** [comment]
The only item missing after #516 is merged is https://github.com/ipfs-shipyard/station/issues/523
