### ISSUE TITLE
Image broken in README

### ISSUE THREAD

**Issue by RichardLitt** [ipfs-shipyard/station#409]
<img width="871" alt="screen shot 2016-10-10 at 1 04 50 pm" src="https://cloud.githubusercontent.com/assets/910753/19244389/28294832-8eea-11e6-8eb9-34375ae3cd96.png">

**Comment by RichardLitt** [comment]
Looks like the issue is that this is down: https://ipfs.io/ipfs/QmaufMhYVWPKwhC1jSb4qHBxgiahrq9ct2hgqk5cZxeE7s

**Comment by dignifiedquire** [comment]
This was pinned on the gateways :/ not a good sign it went away. cc @whyrusleeping @lgierth

**Comment by whyrusleeping** [comment]
@dignifiedquire that hash doesnt show up at all in pinbots pin log. Are you sure it got pinned?

**Comment by dignifiedquire** [comment]
pretty sure, but it was pre 0.4.0

**Comment by dignifiedquire** [comment]
but maybe I also imagine things :/ will see if it is cached on one of my nodes and reprovide when I am back home

**Comment by whyrusleeping** [comment]
SGTM. also hit me up with any hashes you'd like backed up. I'm pinning every hash i can find on my home server

**Comment by diasdavid** [comment]
Works now :)
