### ISSUE TITLE
cannot run on macOS

### ISSUE THREAD

**Issue by satra** [ipfs-shipyard/station#411]
following the instructions in README, results in a blue screen

(on macOS sierra, node/npm 6.8.1)

![image](https://cloud.githubusercontent.com/assets/184063/19411427/b2584844-92cf-11e6-879c-87a038a7021b.png)

**Comment by satra** [comment]
and clicking on `Start Node` crashes the app.

```
error: Uncaught Exception: ENOENT: no such file or directory, open '/Users/satra/.ipfs/config' Error: ENOENT: no such file or directory, open '/Users/satra/.ipfs/config'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at parseConfig (/software/sources/station/node_modules/ipfsd-ctl/lib/node.js:53:17)
    at Node.startDaemon (/software/sources/station/node_modules/ipfsd-ctl/lib/node.js:149:7)
    at onStartDaemon (/software/sources/station/src/init.js:96:8)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/6.8.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! ipfs-station@1.0.0-alpha.1 start: `electron src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ipfs-station@1.0.0-alpha.1 start script 'electron src/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ipfs-station package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron src/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ipfs-station
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ipfs-station
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /software/sources/station/npm-debug.log
```

**Comment by Kuurusch** [comment]
In my case something went wrong during the installation process:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart ipfs-station@1.0.0-alpha.1
6 info start ipfs-station@1.0.0-alpha.1
7 verbose unsafe-perm in lifecycle true
8 info ipfs-station@1.0.0-alpha.1 Failed to exec start script
9 verbose stack Error: ipfs-station@1.0.0-alpha.1 start: `electron src/index.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid ipfs-station@1.0.0-alpha.1
11 verbose cwd /Users/AK47/station
12 error Darwin 16.3.0
13 error argv "node" "/usr/local/bin/npm" "start"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error ipfs-station@1.0.0-alpha.1 start: `electron src/index.js`
17 error Exit status 1
18 error Failed at the ipfs-station@1.0.0-alpha.1 start script 'electron src/index.js'.
18 error This is most likely a problem with the ipfs-station package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     electron src/index.js
18 error You can get their info via:
18 error     npm owner ls ipfs-station
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by luiscarrasco** [comment]
Anybody got this working on OSX?

**Comment by reutopiaer** [comment]
Same problem!
```
mkdir ~/.ipfs && echo "{}" >> ~/.ipfs/config 
````
GVA info: Successfully connected to the Intel plugin, offline Gen9 
error: Uncaught Exception: non-zero exit code 1
  while running: ~/station/node_modules/subcomandante/subcom 95616 ~/station/node_modules/go-ipfs-dep/go-ipfs/ipfs daemon

  Error: no version file in repo at ~/.ipfs

**Comment by Kubuxu** [comment]
As a workaround instead of that try running `ipfs repo init`. The `ipfs` binary wrapper should be somewhere in the `node_modules`.

**Comment by diasdavid** [comment]
Hi there! Station is alive and well again thanks to @hacdias 👏🏽👏🏽👏🏽👏🏽👏🏽👏🏽👏🏽

![image](https://user-images.githubusercontent.com/1211152/33234042-c0289496-d217-11e7-802a-f950d4238776.png)


Try it out again and let us know if you hit an issue. Meanwhile, I'm closing this one :)
