### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs-shipyard/station#52]
- [ ] Components
- [ ] File structure  
- [ ] Used libraries

**Comment by diasdavid** [comment]
@hacdias mind tacking a stab at this?

**Comment by hacdias** [comment]
Hey, yes, I can do this. Should I put it all on README? Or do you have any structure in mind?

**Comment by hacdias** [comment]
Ping @diasdavid

**Comment by diasdavid** [comment]
All in the README.md for now :)
