### ISSUE TITLE
Station crashes when "open directory" dialog is canceled

### ISSUE THREAD

**Issue by machawk1** [ipfs-shipyard/station#521]
macOS 10.13.1
Commit b7e2db666e967b08932a4e3ef7baab7cb16596e3 of **redesign** branch.

Selecting the "folder" icon from the menu UI then hitting the cancel button causes Station to crash with the error
```sh
error: Uncaught Exception: Cannot read property 'length' of undefined {}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ipfs-station@0.1.0 start: `electron-forge start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ipfs-station@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
![station](https://user-images.githubusercontent.com/2514780/33573738-b96a02e0-d904-11e7-9600-8860a9db6c12.gif)

**Comment by hacdias** [comment]
Thank you!! I'll take care ASAP!

**Comment by hacdias** [comment]
Fixed!

**Comment by machawk1** [comment]
Pulled and verified. Thanks for the quick turnaround.
