### ISSUE TITLE
UI: Station popup should hide when context deselection is requested

### ISSUE THREAD

**Issue by machawk1** [ipfs-shipyard/station#522]
In macOS, a common UX pattern is to select (full mousedown-then-mouseup) a menu item, which shows the popup even when the mouse is no longer pressed. Clicking elsewhere when this popup is open closes the popup. For example:

![out](https://user-images.githubusercontent.com/2514780/33577915-bc36a790-d912-11e7-9b57-3b2f96132039.gif)

Station does not allow this "deselection" though. When the Station popup is open and somewhere outside of the popup is clicked, the popup remains visible. Selecting the Station icon again closes the menu but with most programs with a menu item, clicking outside of the popup is usually sufficient. This also means that while Station is displaying its popup, other menu item (e.g., Sound control) can be selected and displayed on top of the Station UI.

![out](https://user-images.githubusercontent.com/2514780/33578100-583ed13a-d913-11e7-9647-5c8b0e2945aa.gif)

...which gets awkward. It would be more natural as a native application if the selection scheme followed that of the system. It might be useful to look at the windowing/display model used by other Electron apps with a menu item to see how they handle this pattern.

**Comment by hacdias** [comment]
We know... I think we're only forcing this to enable drag and drop. On Windows, it is also default to hide the window/popup when you click outside of it. What do you think @diasdavid?

**Comment by machawk1** [comment]
@hacdias Here's another datapoint from [Pushbullet](https://www.pushbullet.com/) menu bar app:

![out](https://user-images.githubusercontent.com/2514780/33581715-ea93c944-d91f-11e7-8575-2d846b780a86.gif)

The "stickiness" is only exhibited here when drag-and-drop is expected, otherwise the popup behaves conventionally and disappears when the context is lost.

**Comment by hacdias** [comment]
@machawk1 yup, we could do that *but* since the left pane defaults to Files, it would always be expected to drag'n'drop unless we had some kind of button to enable drag'n'drop.

**Comment by machawk1** [comment]
@hacdias What if there were some toggle switch, disabled by default, that allowed a user to keep the Station UI visible? This would be useful in cases where they drag-and-drop files en-masse from a variety of locations but less so for one-offs, where they might use the "+" or folder buttons in the bottom right.

Something akin to "pinning" (like a browser tab, though this is a bad term choice due to overloading the IPFS pin concept/cmd) could make such functionality clear and available for those that would use it.
