### ISSUE TITLE
feat: add bandwidth stats to the right pane

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/station#523]
~Add stats to the right pane when https://github.com/ipfs/js-ipfs-api/pull/639 is closed 😄~

https://github.com/ipfs/js-ipfs-api/pull/639 is merged. Will focus on this after we merge #516.

**Comment by diasdavid** [comment]
https://github.com/ipfs/js-ipfs-api/pull/639 merged and released :)
