### ISSUE TITLE
Provide a friendlier message if another daemon is already running on startup

### ISSUE THREAD

**Issue by machawk1** [ipfs-shipyard/station#527]
I often have an IPFS daemon running to interface with other IPFS tools. When launching station, I receive an alert that an instance of the daemon is already running but the message contains the text that one would normally expect on the command-line and not a message typically displayed from a GUI app.

Replicate:
1. Start an IPFS daemon on the system
1. `npm start` from the root of the station working directory

Station 5bd8846a007f9655a451072c23008b162168dd8a
macOS 10.13.1

<img width="532" alt="screen shot 2017-12-05 at 11 41 37 am" src="https://user-images.githubusercontent.com/2514780/33618756-67870236-d9b1-11e7-9875-dc9153dc4d43.png">

**Comment by hacdias** [comment]
What about this:

![image](https://user-images.githubusercontent.com/5447088/33773456-d73cfe66-dc2f-11e7-9cc6-cc953afbe353.png)

**Comment by machawk1** [comment]
:+1: That would be a good initial step.

Also, havea->have a :)

**Comment by hacdias** [comment]
Just updated the image ^^

**Comment by machawk1** [comment]
Much more succinct and to the point.

Is there any plan on eventually allowing the user to use their pre-existing IPFS installation?

**Comment by hacdias** [comment]
I was thinking about the same thing when fixing this issue, I'll create another issue about that.
