### ISSUE TITLE
UI: Adjust menubar icon size to have consistent height among other icons

### ISSUE THREAD

**Issue by machawk1** [ipfs-shipyard/station#528]
<img width="629" alt="screen shot 2017-12-05 at 11 55 19 am" src="https://user-images.githubusercontent.com/2514780/33619415-346a56da-d9b3-11e7-9964-8f9f804dcf79.png">

In an effort to make station appear as fluidly integrated as a system application as possible, one facet that stands out is the height of the menubar icon in comparison to other icons on macOS. Note the difference in height of the station icon comparison to the others, some system provided (e.g., sound, wifi) and other from installed applications (e.g., 1Password, Dropbox)

There is likely a UX standard that addresses this, at least with macOS. I am unsure if it stands out as much on other OSes.

**Comment by hacdias** [comment]
Since I can't really test this, I'd like to ask if you or @diasdavid could take a look at this?

**Comment by diasdavid** [comment]
I believe that what @machawk1 is suggesting is for you to add a bit of padding to the cube :)

**Comment by hacdias** [comment]
Yeah, I know, but I don't know when will be enough. But I'll update it today 😄

**Comment by hacdias** [comment]
I've just updated the icons. Could you check how they look now, please? 😄

**Comment by machawk1** [comment]
That's better but the height of the IPFS cube (dotted blue) is still the largest icon in my menu bar by a few pixels (max height of others in red).

<img width="711" alt="screen shot 2017-12-07 at 10 13 03 am" src="https://user-images.githubusercontent.com/2514780/33722177-475830e8-db37-11e7-8c7b-6b3471450eb6.png">

49274abcc1f7bbdff8c33067d71044764a0ca53f

**Comment by hacdias** [comment]
I reduced them by 18.5% (I got this value by calculating the difference in the image you sent 😄 thanks). Could you check them now, please?

**Comment by machawk1** [comment]
LGTM

<img width="492" alt="screen shot 2017-12-08 at 9 44 26 am" src="https://user-images.githubusercontent.com/2514780/33770631-6b90376a-dbfc-11e7-871c-b554f4c63555.png">

**Comment by hacdias** [comment]
Sweet!
