### ISSUE TITLE
UI: Add functionality to IPFS icon within popup

### ISSUE THREAD

**Issue by machawk1** [ipfs-shipyard/station#532]
I have found myself wondering a few times whether the little IPFS cube in the popup window has functionality associated with it that simply is not working. My guess is that it is there for decoration, which only facilitates this confusion. I can imagine some really useful functionality being tied to this icon but at the moment, it hurts more than it helps. 

![screen shot 2017-12-05 at 6 29 55 pm](https://user-images.githubusercontent.com/2514780/33636591-d7fb448a-d9ea-11e7-92f0-8f4ae77e9d1b.png)

I would like to propose either adding some very fundamental functionality to it to justify its existence in the UI or to remove (or simply hide) it so as to not imply that the app is broken when nothing happens onClick.

**Comment by hacdias** [comment]
I don't know which functionality it could eventually be attached to. Do you have any idea @machawk1 @diasdavid?

**Comment by machawk1** [comment]
@hacdias How about initially using it to toggle the running state of the daemon? Colorized = running, wireframe = not. Even if this was redundant of the other functionality in the window, it gives some purpose to the icon beyond decoration.

**Comment by hacdias** [comment]
@machawk1 Then, the wireframe version wouldn't be used since we have a different screen for when the daemon it's not running. Unless we removed that screen and used something else. Just got an idea!
