### ISSUE TITLE
Update stats on window show

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs-shipyard/station#60]
At the moment depending on the timeout position there is a delay between opening the profile screen and the stats updating. We should listen for the window `show` event and update the stats at that point.

**Comment by swang** [comment]
Hi, I would like to work on this, should this thing only poll when the profile screen gets opened or should it still continue to poll in the background like it seems to do now?

**Comment by dignifiedquire** [comment]
Looking forward to it :) below a hopefully better description of what should ideally happen

- It should not poll while the window is hidden to minimize the background activity when not used. 
- On window `show` it should update, and then start the polling.
- When the window is closed the polling should be stopped
